import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pymupdf  # PyMuPDF
import pymupdf4llm

from rag_project.config import DEFAULT_PDF_PATH, HEADER_FOOTER_PATTERNS, IGNORE_SECTIONS

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


class PDFParser:
    """High-accuracy layout-aware technical PDF parser using PyMuPDF4LLM and hierarchical TOC mapping.
    Extracts structured markdown, intact tabular matrices, figure proxies, and strips schematic/drawing noise.
    """

    def __init__(self, pdf_path: Optional[str] = None):
        self.pdf_path = Path(pdf_path) if pdf_path else DEFAULT_PDF_PATH
        if not self.pdf_path.exists():
            raise FileNotFoundError(f"PDF file not found at {self.pdf_path}")

    def clean_markdown_text(self, text: str) -> str:
        """Thorough multi-stage cleaner for PDF extraction artifacts, vector OCR drawings, headers, and footers."""
        if not text:
            return ""

        # Step 0: Remove null bytes
        text = text.replace("\x00", "")

        # Step 1: Multi-line vector schematic & picture text block purging
        text = re.sub(r"<!--\s*Start of picture text\s*-->.*?<!--\s*End of picture text\s*-->", "", text, flags=re.DOTALL | re.IGNORECASE)
        text = re.sub(r"<!--\s*Start of picture text\s*-->", "", text, flags=re.IGNORECASE)
        text = re.sub(r"<!--\s*End of picture text\s*-->", "", text, flags=re.IGNORECASE)

        # Step 2: Remove HTML markup artifacts generated by layout OCR
        text = re.sub(r"<br\s*/?>", "\n", text, flags=re.IGNORECASE)
        text = re.sub(r"</?(?:sup|sub|u|b|i|span|div|p)>", "", text, flags=re.IGNORECASE)

        # Step 3: Remove strikethrough artifacts from header detectors
        text = re.sub(r"_?~~(.*?)~~_?", r"\1", text)

        # Step 4: Line-by-line pattern filtering
        lines = text.split("\n")
        cleaned_lines = []

        for line in lines:
            stripped = line.strip()
            if not stripped:
                cleaned_lines.append("")
                continue

            # Check configured header / footer stripping patterns
            should_skip = False
            for pat in HEADER_FOOTER_PATTERNS:
                if re.search(pat, stripped, re.IGNORECASE):
                    should_skip = True
                    break
            if should_skip:
                continue

            # Skip standalone page numbers (e.g. "43", "**43**", "_43_")
            if re.match(r"^(?:\*{0,2}|_{0,2})\d+(?:\*{0,2}|_{0,2})\s*$", stripped):
                continue

            # Skip lonely website or feedback links
            if re.match(r"^(?:www\.xilinx\.com|send feedback|ug\d+\s*\(v[\d\.]+\))\s*$", stripped, re.IGNORECASE):
                continue

            # Skip empty markdown table rows (e.g. | | | | or |---|---|)
            if re.match(r"^\s*\|\s*(?:\|\s*)+$", stripped):
                continue

            # Skip isolated vector drawing labels & coordinate tags (e.g. UG389_c2_01_052609)
            if re.match(r"^(?:UG|PG)\d+_[a-z0-9_]+$", stripped, re.IGNORECASE):
                continue

            # Skip drawing operator noise lines (e.g. isolated "a.real", "b.img", "m  p", "z -2")
            if re.match(r"^(?:[abp]\.(?:real|img)|[mpcz]\s*-?\d*|\d+\s*×\s*\+)\s*$", stripped, re.IGNORECASE):
                continue

            cleaned_lines.append(line)

        cleaned = "\n".join(cleaned_lines)

        # Step 5: Normalize multiple consecutive linebreaks
        cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
        return cleaned.strip()

    def classify_content_type(self, text: str) -> str:
        """Determine content type primitive: atomic_table, figure_proxy, code_template, register_spec, timing, or prose."""
        lower = text.lower()
        if "|" in text and ("| ---" in text or "|:---" in text or text.count("\n|") >= 2):
            return "atomic_table"
        if re.search(r"Figure\s+\d+-\d+:", text, re.IGNORECASE):
            return "figure_proxy"
        if any(code_indicator in text for code_indicator in ["```verilog", "```vhdl", "```c", "entity ", "architecture ", "module ", "endmodule"]):
            return "code_template"
        if any(term in lower for term in ["clock latency", "clock cycle", "setup time", "hold time", "timing diagram", "clock-to-out", "read latency", "latency"]):
            return "timing"
        if any(term in lower for term in ["signal name", "direction", "active polarity", "pinout", "pin description", "port description", "opmode", "carryin", "carryout"]):
            return "register_spec"
        return "narrative_text"

    def is_blacklisted_section(self, title: str, text: str) -> bool:
        """Check if section is non-technical frontmatter or backmatter (TOC, Legal, Additional Resources)."""
        check_str = f"{title}\n{text}".lower()
        for ign in IGNORE_SECTIONS:
            ign_lower = ign.lower()
            if ign_lower in title.lower():
                return True
            # For whole text, match explicit headers
            if re.search(rf"(?:^|\n)#{1,3}\s+.*{re.escape(ign_lower)}", check_str, re.IGNORECASE):
                return True
            if re.search(rf"\b{re.escape(ign_lower)}\b", title, re.IGNORECASE):
                return True
        return False

    def build_page_toc_map(self, doc: pymupdf.Document) -> Dict[int, Dict[str, str]]:
        """Build a mapping from page number to hierarchical TOC items."""
        toc = doc.get_toc()
        page_toc: Dict[int, Dict[str, str]] = {}

        current_section_i = "Overview"
        current_chapter = "Overview"
        current_title = "Overview"

        for lvl, title, page_num in toc:
            clean_title = title.strip()
            if lvl == 1 or lvl == 2:
                current_section_i = clean_title
                current_chapter = clean_title
                current_title = clean_title
            elif lvl == 3:
                current_chapter = clean_title
                current_title = clean_title
            elif lvl >= 4:
                current_title = clean_title

            breadcrumb = f"{current_section_i} > {clean_title}" if current_section_i != clean_title else current_section_i
            page_toc[page_num] = {
                "section": current_section_i,
                "chapter": current_chapter,
                "title": clean_title,
                "breadcrumb": breadcrumb
            }

        return page_toc

    @staticmethod
    def clean_cell_text(val: Any) -> str:
        """Clean and normalize individual table cell text."""
        if val is None:
            return ""
        text = str(val).strip()
        text = re.sub(r"([A-Za-z])\s+-\s*([A-Za-z])", r"\1-\2", text)
        text = re.sub(r"Dual\s+-port", "Dual-port", text, flags=re.I)
        text = re.sub(r"Single\s+-port", "Single-port", text, flags=re.I)
        text = re.sub(r"Single-por\s+t\s+RAM", "Single-port RAM", text, flags=re.I)
        text = re.sub(r"Width\s*x?\s*Depth", "Width x Depth", text, flags=re.I)
        text = re.sub(r"Performance\s*\(MHz\)", "Performance (MHz)", text, flags=re.I)
        return " ".join(text.split())

    def format_native_table(self, table_obj: Any, caption: str = "", footnotes: Optional[List[str]] = None) -> str:
        """Format PyMuPDF table object into clean Markdown with hierarchical headers and forward-filled rowspans."""
        raw_df = table_obj.extract()
        if not raw_df or len(raw_df) < 2:
            return ""

        num_cols = max(len(r) for r in raw_df)
        grid = [list(r) + [None] * (num_cols - len(r)) for r in raw_df]
        clean_grid = [[self.clean_cell_text(c) for c in row] for row in grid]

        header_end_idx = 1
        for r_idx in range(len(clean_grid)):
            row = clean_grid[r_idx]
            col0 = row[0].lower()
            col1 = row[1].lower() if len(row) > 1 else ""
            col2 = row[2].lower() if len(row) > 2 else ""

            if any(col0.startswith(prefix) for prefix in ["true dual", "single-port", "dual-port", "simple dual", "rom", "ram", "distributed", "a", "b", "c", "d", "0", "1"]):
                header_end_idx = r_idx
                break
            if re.search(r"^\d+x\d+[kK]?$", col1) or re.search(r"^\d+x\d+[kK]?$", col2):
                header_end_idx = r_idx
                break
            num_count = sum(1 for c in row if re.match(r"^\d+$", c))
            if num_count >= 2:
                header_end_idx = r_idx
                break

        if header_end_idx == 0:
            header_end_idx = 1

        header_rows = clean_grid[:header_end_idx]
        data_rows = clean_grid[header_end_idx:]

        # Build composite column headers
        composite_cols = []
        for c_idx in range(num_cols):
            col_parts = []
            for h_row in header_rows:
                val = h_row[c_idx]
                if val and val not in col_parts and val != "-":
                    col_parts.append(val)
            composite_cols.append(" ".join(col_parts) if col_parts else f"Col_{c_idx+1}")

        final_cols = []
        for c in composite_cols:
            col = c
            col = re.sub(r"Resource\s*Utilization\s*Block\s*RAMs?\s*(\d+K?)", r"Block RAMs (\1)", col, flags=re.I)
            col = re.sub(r"Block\s*RAM\s*(\d+K?)", r"Block RAMs (\1)", col, flags=re.I)
            col = re.sub(r"Resource\s*Utilization\s*(Shift\s*Regs|FFs|LUTs\w*|Virtex-\d+)", r"\1", col, flags=re.I)
            col = re.sub(r"Output\s*Register\s*Options?", "Output Register Options", col, flags=re.I)
            col = re.sub(r"Width\s*x?\s*Depth", "Width x Depth", col, flags=re.I)
            final_cols.append(col)

        filled_data = []
        last_row_values = [""] * num_cols

        for row in data_rows:
            current_filled = list(row)
            for col_idx in range(num_cols):
                val = current_filled[col_idx]
                if not val or val == "-":
                    if col_idx < 3 and last_row_values[col_idx]:
                        current_filled[col_idx] = last_row_values[col_idx]
                    else:
                        current_filled[col_idx] = "-"
                else:
                    current_filled[col_idx] = val
                    last_row_values[col_idx] = val
            filled_data.append(current_filled)

        md_lines = []
        if caption:
            md_lines.append(caption.strip())
            md_lines.append("")

        md_lines.append("| " + " | ".join(final_cols) + " |")
        md_lines.append("| " + " | ".join([":---"] * num_cols) + " |")
        for r in filled_data:
            md_lines.append("| " + " | ".join(r) + " |")

        if footnotes:
            md_lines.append("")
            for fn in footnotes:
                md_lines.append(fn)

        return "\n".join(md_lines)

    def decompose_page_blocks(
        self,
        cleaned_text: str,
        page_num: int,
        toc_meta: Dict[str, str]
    ) -> List[Dict[str, Any]]:
        """Decompose cleaned text into semantic DOM blocks (atomic tables, figure proxies, narrative sections)."""
        if not cleaned_text or len(cleaned_text.strip()) < 20:
            return []

        active_chapter = toc_meta.get("chapter", "Overview")
        active_section = toc_meta.get("section", "Overview")
        active_title = toc_meta.get("title", active_section)

        lines = cleaned_text.split("\n")
        blocks = []
        current_lines = []
        current_type = "narrative_text"
        current_title = active_title
        current_anchor = ""

        i = 0
        while i < len(lines):
            line = lines[i]
            stripped = line.strip()

            table_match = re.match(r"^(?:_|\*\*|#+\s*)?Table\s+(\d+[-–]\d+):?\s*(?:_|\*\*)?\s*(.*)$", stripped, re.IGNORECASE)
            figure_match = re.match(r"^(?:_|\*\*|#+\s*)?Figure\s+(\d+[-–]\d+):?\s*(?:_|\*\*)?\s*(.*)$", stripped, re.IGNORECASE)
            header_match = re.match(r"^#{1,3}\s+(.+)$", stripped)

            if table_match:
                if current_lines:
                    txt = "\n".join(current_lines).strip()
                    if txt:
                        blocks.append({
                            "document_name": self.pdf_path.name,
                            "page_number": page_num,
                            "section_title": current_title,
                            "chapter": active_chapter,
                            "section": active_section,
                            "breadcrumb": f"{active_chapter} > {current_title}",
                            "content_type": current_type,
                            "anchor": current_anchor,
                            "markdown": txt,
                        })
                    current_lines = []

                current_type = "atomic_table"
                tbl_num = table_match.group(1).replace("–", "-")
                tbl_title = table_match.group(2).strip().strip("*_").strip()
                current_anchor = f"Table {tbl_num}: {tbl_title}".strip(": ")
                current_title = current_anchor
                current_lines.append(f"_Table {tbl_num}:_ **{tbl_title}**" if tbl_title else f"_Table {tbl_num}_")
                i += 1
                continue

            elif figure_match:
                if current_lines:
                    txt = "\n".join(current_lines).strip()
                    if txt:
                        blocks.append({
                            "document_name": self.pdf_path.name,
                            "page_number": page_num,
                            "section_title": current_title,
                            "chapter": active_chapter,
                            "section": active_section,
                            "breadcrumb": f"{active_chapter} > {current_title}",
                            "content_type": current_type,
                            "anchor": current_anchor,
                            "markdown": txt,
                        })
                    current_lines = []

                current_type = "figure_proxy"
                fig_num = figure_match.group(1).replace("–", "-")
                fig_title = figure_match.group(2).strip().strip("*_").strip()
                current_anchor = f"Figure {fig_num}: {fig_title}".strip(": ")
                current_title = current_anchor
                current_lines.append(f"**Figure {fig_num}: {fig_title}**" if fig_title else f"**Figure {fig_num}**")
                i += 1
                continue

            elif header_match and current_type != "atomic_table":
                if current_lines:
                    txt = "\n".join(current_lines).strip()
                    if txt:
                        blocks.append({
                            "document_name": self.pdf_path.name,
                            "page_number": page_num,
                            "section_title": current_title,
                            "chapter": active_chapter,
                            "section": active_section,
                            "breadcrumb": f"{active_chapter} > {current_title}",
                            "content_type": current_type,
                            "anchor": current_anchor,
                            "markdown": txt,
                        })
                    current_lines = []

                current_title = header_match.group(1).strip()
                current_type = self.classify_content_type(line)
                current_anchor = ""
                current_lines.append(line)
                i += 1
                continue

            current_lines.append(line)
            i += 1

        if current_lines:
            txt = "\n".join(current_lines).strip()
            if txt:
                blocks.append({
                    "document_name": self.pdf_path.name,
                    "page_number": page_num,
                    "section_title": current_title,
                    "chapter": active_chapter,
                    "section": active_section,
                    "breadcrumb": f"{active_chapter} > {current_title}",
                    "content_type": current_type,
                    "anchor": current_anchor,
                    "markdown": txt,
                })

        return blocks

    def extract_page_by_page(self) -> List[Dict[str, Any]]:
        """Extract structured pages using native PyMuPDF table geometry and PyMuPDF4LLM prose extraction."""
        doc = pymupdf.open(str(self.pdf_path))
        page_toc = self.build_page_toc_map(doc)
        total_pages = len(doc)

        logger.info(f"Parsing '{self.pdf_path.name}' ({total_pages} pages) via PyMuPDF + PyMuPDF4LLM...")
        try:
            md_pages = pymupdf4llm.to_markdown(str(self.pdf_path), page_chunks=True)
        except Exception as e:
            logger.warning(f"PyMuPDF4LLM batch parsing fallback: {e}")
            md_pages = []

        raw_blocks = []
        cur_toc = {"section": "Overview", "chapter": "Overview", "title": "Overview", "breadcrumb": "Overview"}

        for page_idx in range(total_pages):
            page_num = page_idx + 1
            if page_num in page_toc:
                cur_toc = page_toc[page_num]

            page = doc[page_idx]
            raw_text = md_pages[page_idx].get("text", "") if page_idx < len(md_pages) else page.get_text("text")

            # Blacklist check
            if self.is_blacklisted_section(cur_toc.get("title", ""), raw_text):
                continue
            if page_num <= 4 and any(ign.lower() in raw_text.lower() for ign in ["revision history", "table of contents", "notice of disclaimer"]):
                continue
            if page_num >= total_pages - 2 and any(ign.lower() in raw_text.lower() for ign in ["additional resources", "references"]):
                continue

            cleaned_text = self.clean_markdown_text(raw_text)
            if not cleaned_text or len(cleaned_text.strip()) < 15:
                continue

            # Detect native tables on this page
            tabs = page.find_tables()
            if tabs.tables:
                text_blocks = page.get_text("blocks")
                table_bboxes = []
                table_sections = []
                caption_block_indices = set()
                footnote_block_indices = set()

                for t_idx, tab in enumerate(tabs.tables):
                    tx0, ty0, tx1, ty1 = tab.bbox
                    table_bboxes.append((tx0, ty0, tx1, ty1))

                    best_caption = ""
                    for b_idx, blk in enumerate(text_blocks):
                        bx0, by0, bx1, by1, btext, _, _ = blk
                        if by1 <= ty0 + 8 and ty0 - by1 < 45:
                            clean_b = " ".join(btext.split())
                            if re.search(r"Table\s+\d+[-–]\d+", clean_b, re.I):
                                best_caption = clean_b
                                caption_block_indices.add(b_idx)
                                break

                    best_footnotes = []
                    for b_idx, blk in enumerate(text_blocks):
                        bx0, by0, bx1, by1, btext, _, _ = blk
                        if by0 >= ty1 - 8 and by0 - ty1 < 45:
                            clean_b = " ".join(btext.split())
                            if re.match(r"^[a-z]\.\s+", clean_b, re.I) or clean_b.startswith("Note:"):
                                best_footnotes.append(clean_b)
                                footnote_block_indices.add(b_idx)

                    m = re.search(r"Table\s+(\d+[-–]\d+):?\s*(.*)", best_caption, re.I)
                    if m:
                        tbl_title = f"Table {m.group(1).replace('–', '-')}: {m.group(2).strip('*_ ')}"
                    else:
                        tbl_title = best_caption if best_caption else f"Table on Page {page_num}"

                    formatted_md = self.format_native_table(tab, caption=f"_{tbl_title}_", footnotes=best_footnotes)
                    if formatted_md:
                        table_sections.append({
                            "document_name": self.pdf_path.name,
                            "page_number": page_num,
                            "section_title": tbl_title,
                            "chapter": cur_toc.get("chapter", "Overview"),
                            "section": cur_toc.get("section", "Overview"),
                            "breadcrumb": f"{cur_toc.get('chapter', 'Overview')} > {tbl_title}",
                            "content_type": "atomic_table",
                            "anchor": tbl_title,
                            "markdown": formatted_md,
                            "bbox_y0": ty0
                        })

                # Extract non-table prose
                narrative_paragraphs = []
                for b_idx, blk in enumerate(text_blocks):
                    if b_idx in caption_block_indices or b_idx in footnote_block_indices:
                        continue
                    bx0, by0, bx1, by1, btext, _, _ = blk
                    in_table = False
                    for tx0, ty0, tx1, ty1 in table_bboxes:
                        if bx0 >= tx0 - 5 and bx1 <= tx1 + 5 and by0 >= ty0 - 5 and by1 <= ty1 + 5:
                            in_table = True
                            break
                    if in_table:
                        continue

                    clean_text = " ".join(btext.split())
                    if not clean_text or len(clean_text) < 15:
                        continue
                    if any(ign in clean_text.lower() for ign in ["pg058", "ug380", "ug389", "pg036", "pg065", "ug682", "www.xilinx.com"]):
                        if len(clean_text) < 60:
                            continue

                    narrative_paragraphs.append((by0, clean_text))

                page_elements = []
                for ts in table_sections:
                    page_elements.append((ts["bbox_y0"], ts))

                if narrative_paragraphs:
                    narr_text = "\n\n".join(p[1] for p in narrative_paragraphs)
                    first_y = narrative_paragraphs[0][0]
                    page_elements.append((first_y, {
                        "document_name": self.pdf_path.name,
                        "page_number": page_num,
                        "section_title": cur_toc.get("title", cur_toc.get("section", "Overview")),
                        "chapter": cur_toc.get("chapter", "Overview"),
                        "section": cur_toc.get("section", "Overview"),
                        "breadcrumb": cur_toc.get("breadcrumb", f"{cur_toc.get('chapter', 'Overview')} > {cur_toc.get('section', 'Overview')}"),
                        "content_type": self.classify_content_type(narr_text),
                        "anchor": "",
                        "markdown": narr_text
                    }))

                page_elements.sort(key=lambda x: x[0])
                for _, elem in page_elements:
                    elem.pop("bbox_y0", None)
                    raw_blocks.append(elem)
            else:
                page_blocks = self.decompose_page_blocks(cleaned_text, page_num, cur_toc)
                raw_blocks.extend(page_blocks)

        doc.close()

        # Apply Cross-Page AST Boundary Snapping & Continuation Table Stitching
        consolidated = self.stitch_cross_page_sections(raw_blocks)
        return consolidated

    def stitch_cross_page_sections(self, sections: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Stitch continuation tables and sentences spanning across physical page breaks."""
        if not sections or len(sections) <= 1:
            return sections

        stitched = [sections[0]]
        for curr in sections[1:]:
            prev = stitched[-1]

            is_consecutive_page = (curr["page_number"] == prev["page_number"] + 1)
            
            # Case A: Cross-page Continuation Table
            if is_consecutive_page and prev["content_type"] == "atomic_table" and curr["content_type"] == "atomic_table" and not curr.get("anchor"):
                prev_lines = prev["markdown"].rstrip().split("\n")
                curr_lines = [l for l in curr["markdown"].split("\n") if l.strip()]
                if len(curr_lines) >= 2 and curr_lines[0].startswith("|") and ("|---" in curr_lines[1] or "|:---" in curr_lines[1]):
                    curr_lines = curr_lines[2:]
                prev["markdown"] = "\n".join(prev_lines + curr_lines)
                prev["pages"] = f"{prev['page_number']}-{curr['page_number']}"
                continue

            # Case B: Cross-page sentence cut
            if is_consecutive_page and prev["content_type"] == "narrative_text" and curr["content_type"] == "narrative_text":
                prev_md = prev["markdown"].rstrip()
                curr_md = curr["markdown"].lstrip()
                ends_unclosed = (
                    bool(re.search(r"[,;\-\(]\s*$", prev_md)) or
                    (not bool(re.search(r"[\.!\?:\`\"]\s*$", prev_md)) and not prev_md.endswith("|"))
                )
                starts_without_heading = not bool(re.match(r"^#{1,4}\s+", curr_md))
                if ends_unclosed and starts_without_heading:
                    prev["markdown"] = prev_md + " " + curr_md
                    continue

            stitched.append(curr)

        return stitched


